# Enable mouse mode
set -g mouse on

# Enable status bar
set -g status on

# Vi copy mode
set -g mode-keys vi

# When creating or splitting new panes, keep working directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# By default, tmux uses login shells. Don't do that
# On many systems this means bashrc won't be sourced
set -g default-command "${SHELL}"

# Rename tabs to current command's basename
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_command}'

# Let tmux and applications inside tmux copy to system clipboard
set -g set-clipboard on

